### ISSUE TITLE
500 on GET /admin/sources when there is no sources

### ISSUE THREAD

**Issue by gallypette** [flowintel/cocktailparty#19]
```
cocktailparty@elixir-http-01 2023-12-14 08:20:53.946 error #PID<0.2448.0> running CocktailpartyWeb.Endpoint (connection #PID<0.2425.0>, stream id 16) terminated
Server: broker.d4-project.org:80 (http)
Request: GET /admin/sources
** (exit) an exception was raised:
    ** (KeyError) key :name not found in: nil

If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
        (cocktailparty 0.1.0) lib/cocktailparty_web/controllers/admin/../source_html/index.html.heex:21: anonymous fn/3 in CocktailpartyWeb.Admin.SourceHTML.index/1
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/engine.ex:137: Phoenix.HTML.Safe.Phoenix.LiveView.Rendered.to_iodata/1
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/engine.ex:92: Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/2
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/engine.ex:97: Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/2
        (elixir 1.15.2) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
        (elixir 1.15.2) lib/enum.ex:1693: Enum."-map/2-lists^map/1-1-"/2
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/engine.ex:92: Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/2
        (phoenix_live_view 0.18.18) lib/phoenix_live_view/engine.ex:97: Phoenix.HTML.Safe.Phoenix.LiveView.Comprehension.to_iodata/2
```

**Comment by gallypette** [comment]
nope -- it happens because of the migration from the old system where there was only one migration.
